name: deploy and publish
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # if: github.repository == 'SocialSisterYi/bilibili-API-collect'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: vuepress-deploy
      uses: IT4Change/vuepress-build-and-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: .vuepress/dist/
